### ISSUE TITLE
really love this but..

### ISSUE THREAD

**Issue by vesper8** [EriBloo/laravel-model-snapshots#10]
Hey there! 

First of all thanks so much for making this! When I first found it just now after banging my head against a BIG problem for hours I thought OMG this does everything I need!!!

But then after installing it and playing with it for about 30 minutes.. I realize that no.. unfortunately it doesn't do (yet) what I need it to do. That is, it doesn't seem currently suited to handle snapshotting of parent model and all of its nested relations as well... this is a much more complex issue I guess.. but I actually think your awesome package is an excellent foundation for adding this functionality.

I'd like to talk a bit about what I'd love for you package to be able to accomplish, but before I do.. I guess there may be a part I'm not understanding about your current package? What is the purpose of the model_snapshot_relations and how come no matter what I do I don't ever see any rows being written to it? A short example showing the intended use of that table would be useful!

Anyhow.. what I really need is to be able to take a snapshot of a model, all of its related models, and all of theirs. This can end up being a very large json dump. And of course I also need to be able to convert that back into eloquent models. I wonder if you ever thought about that? I'd really love to pick your brain over that if you have any time. Happy to buy you a coffee or a beer over it too.

I've already begun attempting to do this before I found out about your package. Saving a big json dump is the easy part of course. I'm trying to re-hydrate from the snapshot, in my current use case I don't need those models to be saved to the db necessarily, I just need for them to be rehydrated into eloquent models with fully functional relationships so that I can pass that back to my frontend. This is proving to be a bit challenging and tedious but totally possible through a combination of `(new Model)->newFromBuilder()` and `setRelation`.

It would have been a godsend if your package was capable of handling that. Just how out of scope do you think that is right now?

Hey thanks again! Hope you see this and have time to reply! I'm serious about the beer ;-)

**Comment by EriBloo** [comment]
Hi,

thanks for kind words.

Thing you described is something that I thought about too, but didn't add (yet?). I didn't like storing everything in one json. Problems with restoring such structure is exactly what I was thinking would happen. I may rethink it to have a separate json for relations or maybe separate connected snapshots.

`model_snapshot_relations` is being used in `HasSnapshotRelations` [trait](https://github.com/EriBloo/laravel-model-snapshots#traits). I will describe it with example which is actually a motivation, why I created this package:

We often need to keep versions of objects the moment they were when something happened (eg. a product when order was made). In my case, I have documents created in a system by employees, that they can freely edit and clients can accept them (lets say "I have read the terms and conditions" type). I wanted to keep the version of document the state it was in that moment.

So I have `HasSnapshots` trait oin `Document` model and `HasSnapshotRelations` in `User`. Than I can add:

```php
// User.php

public function acceptedDocuments(): MorphSnapshotModels
{
    return $this->morphSnapshotAsModels(Document::class);
}
```

and when user accepts a document i would do:

```php
$user->acceptedDocuments()->attach(snapshot($document)->commit());
```

I can then retrieve `acceptedDocuments` on `User` and they would be of `Document` instance (not `Snapshot`), exactly the same as if I made a relation with `Document`.

I hope this clears up a bit what I had in mind. I'm not the best at writing documentation 😄
