### ISSUE TITLE
Laravel 11.19 breaks this package

### ISSUE THREAD

**Issue by vesper8** [EriBloo/laravel-model-snapshots#16]
In Laravel 11.19 (https://github.com/laravel/framework/releases/tag/v11.19.0) this PR was added:

https://github.com/laravel/framework/pull/52227

This causes this query:

```
        $snapshot = $this->snapshot
            ->newQuery()
            ->whereMorphedTo($this->snapshot->subject(), $this->model->getMorphClass())
            ->latest()
            ->first();
```

To result in this SQL:

```

select * from `model_snapshots` where `related_table`.`subject_type` = ? order by `created_at` desc
```

Instead of

```

select * from `model_snapshots` where `subject_type` = ? order by `created_at` desc
```

Basically it looks for `subject_type` on the related_table instead of on the model_snapshots table.

I'm not entirely sure why this is happening.. perhaps the `whereMorphedTo` method is the wrong method to use here?

Any chance you could fix this query so that it explicitly looks for `subject_type` to avoid this issue?

Something like this perhaps

```

$snapshot = $this->snapshot
    ->newQuery()
    ->where(function ($query) {
        $query->where('subject_type', $this->model->getMorphClass());
    })
    ->latest()
    ->first();
```

Many thanks!

**Comment by EriBloo** [comment]
Hi.
Thanks for info. I will fix this soon.

Cheers!

**Comment by EriBloo** [comment]
This should be fixed now ;)

**Comment by vesper8** [comment]
Yay awesome thank you!
